//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleTexts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab2.Properties.ConsoleTexts", typeof(ConsoleTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введене значення має бути цілим числом в межах від 1950 до 2010. Спробуйте знову:.
        /// </summary>
        internal static string BirthYearInputErrorMessage {
            get {
                return ResourceManager.GetString("BirthYearInputErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такої опції не існує. Спробуйте знову..
        /// </summary>
        internal static string CommandInputErrorMessage {
            get {
                return ResourceManager.GetString("CommandInputErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть кількість студентів, яку бажаєте записати в файл:.
        /// </summary>
        internal static string CreateStudentXmlFileStartMessage {
            get {
                return ResourceManager.GetString("CreateStudentXmlFileStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML файл для збереження інформації про студентів випускників був створений успішно!.
        /// </summary>
        internal static string CreateStudentXmlFileSuccessMessage {
            get {
                return ResourceManager.GetString("CreateStudentXmlFileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть кількість керівників, яку бажаєте записати в файл:.
        /// </summary>
        internal static string CreateSupervisorXmlFileStartMessage {
            get {
                return ResourceManager.GetString("CreateSupervisorXmlFileStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML файл для збереження інформації про наукових керівників був створений успішно!.
        /// </summary>
        internal static string CreateSupervisorXmlFileSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSupervisorXmlFileSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введене значення має бути типу DateTime. Спробуйте знову:.
        /// </summary>
        internal static string DateTimeParseErrorMessage {
            get {
                return ResourceManager.GetString("DateTimeParseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введене значення має бути числом від 60 до 100. Спробуйте знову:.
        /// </summary>
        internal static string DoubleParseErrorMessage {
            get {
                return ResourceManager.GetString("DoubleParseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студентів, підпадаючих під задані параметри, знайдено не було..
        /// </summary>
        internal static string EmptyStudentListMessage {
            get {
                return ResourceManager.GetString("EmptyStudentListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть номер команди(exit для виходу з програми):.
        /// </summary>
        internal static string EnterCommandNumberMessage {
            get {
                return ResourceManager.GetString("EnterCommandNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Натисність будь-яку клавішу для виходу з програми....
        /// </summary>
        internal static string FinalMessage {
            get {
                return ResourceManager.GetString("FinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Натисність будь-яку клавішу для завершення програми...
        /// </summary>
        internal static string FinishMessage {
            get {
                return ResourceManager.GetString("FinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найбільший середній бал студента - .
        /// </summary>
        internal static string HighestStudentScoreCommandMsg {
            get {
                return ResourceManager.GetString("HighestStudentScoreCommandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введене значення має бути числом цілого типу, більше нуля. Спробуйте знову:.
        /// </summary>
        internal static string IntParseErrorMessage {
            get {
                return ResourceManager.GetString("IntParseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 - Створити або перезаписати XML-файл для зберігання інформації про наукових керівників
        ///2 - Створити або перезаписати XML-файл для зберігання інформаціх про студентів-випускників
        ///3 - Переглянути вміст створеного файлу для зберігання інформації про наукових керівників
        ///4 - Переглянути вміст створеного файлу для зберігання інформації про студентів-випускників
        ///5 - Отримати значення найвищого середнього балу серед усіх студентів-випускників
        ///6 - Змінити значення середнього балу студента
        ///7 - Отримати кількі [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некоректний ввід. Введене значення має бути цілого типу від 1 до 22..
        /// </summary>
        internal static string MenuChoiceErrorMessage {
            get {
                return ResourceManager.GetString("MenuChoiceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть одну з запропонованих опцій(exit для виходу з меню):.
        /// </summary>
        internal static string MenuNavigateMessage {
            get {
                return ResourceManager.GetString("MenuNavigateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середнє значення середнього балу всіх студентів - .
        /// </summary>
        internal static string StudentAverageScoreMessage {
            get {
                return ResourceManager.GetString("StudentAverageScoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформація про студента:.
        /// </summary>
        internal static string StudentDataMessage {
            get {
                return ResourceManager.GetString("StudentDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введена група містить таку кількість студентів - .
        /// </summary>
        internal static string StudentGroupAmountCommandMsg {
            get {
                return ResourceManager.GetString("StudentGroupAmountCommandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студента з таким ім&apos;ям не існує. Спробуйте знову:.
        /// </summary>
        internal static string StudentSearchByFullNameErrorMessage {
            get {
                return ResourceManager.GetString("StudentSearchByFullNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформація про наукового керівника:.
        /// </summary>
        internal static string SupervisorDataMessage {
            get {
                return ResourceManager.GetString("SupervisorDataMessage", resourceCulture);
            }
        }
    }
}
